development:
    dialect: postgres
    datasource: test.db
    dir: migrations/postgres

production:
    dialect: postgres
    datasource: dbname=myapp sslmode=disable
    dir: migrations/postgres
    table: migrations